# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        HGT\Application\User\Customer\Customer: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        accounts:
            entity: { class: HGT\Application\User\Customer\Customer, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - HGT\AppBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout

            switch_user: ~

    access_control:
        - { path: ^/mijn-account, roles: ROLE_CUSTOMER }
        - { path: ^/cart, roles: ROLE_CUSTOMER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
