# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    HGT\AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,DataFixtures,Traits}'

    HGT\Application\:
        resource: '../../src/Application/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/Application/{Entity,Repository,DataFixtures,Traits}'

    HGT\AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    HGT\AppBundle\DataFixtures\ORM\LoadFixtures:
        tags: ['doctrine.fixture.orm']

    HGT\AppBundle\Mailer\Sender\Mailer:
        arguments:
            - ""
            - ""
            - "%mailer_default_from_email%"
            - "%mailer_default_from_name%"

    HGT\AppBundle\Mailer\Cart\OrderSender:
        arguments:
            - "%mailer_default_to_order_cc_name%"
            - "%mailer_default_to_order_cc_email%"
            - "%mailer_default_to_order_name%"
            - "%mailer_default_to_order_email%"
            - ""

    HGT\AppBundle\Security\PasswordEncoder:
        arguments:
            - ""
            - "%salt%"

    HGT\Application\Content\NewsletterService:
        arguments:
            - "%mailchimp_api_key%"

    HGT\AppBundle\Mailer\Sender\CustomerProductRemovalSender:
        arguments:
            - "%mailer_default_to_order_name%"
            - "%mailer_default_to_order_email%"
            - ""

    HGT\Application\Catalog\WebOrderService:
        arguments:
            - "%xml_export_dir%"
            - ""
            - ""
            - ""

    HGT\AppBundle\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }
